version: "3.8"

networks:
  tevian_net:

services:
  db:
    container_name: db_tevian
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tevian_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: api_tevian
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - CLOUD_PASSWORD=${CLOUD_PASSWORD}
      - CLOUD_LOGIN=${CLOUD_LOGIN}
      - SERVICE_LOGIN=${SERVICE_LOGIN}
      - SERVICE_PASSWORD=${SERVICE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tevian_net

  migrate:
    restart: on-failure
    image: migrate/migrate
    networks:
      - tevian_net
    volumes:
      - ./database/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}?sslmode=disable", "up", "3"]

volumes:
  db_data:
