version: "3.8"

services:
  app:
    container_name: api_tevian
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - CLOUD_PASSWORD=${CLOUD_PASSWORD}
      - CLOUD_LOGIN=${CLOUD_LOGIN}
    depends_on:
      - db
  db:
    container_name: db_tevian
    image: postgres:15
    environment:
      - POSTGRES_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_PORT=${POSTGRESQL_PORT}
      - POSTGRES_HOST=${POSTGRESQL_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
